#!/usr/bin/env bash
# ------------------------------------------------------------------ #
# build.sh — 4328 CPU project build script
# Targets: GHDL (simulation) and Vivado (synthesis, optional)
# ------------------------------------------------------------------ #
set -euo pipefail

# ------------------------------------------------------------------ #
# Config
# ------------------------------------------------------------------ #
TOP=top # top-level entity for sim (change to top for synthesis)
WORK=work
STD=08                         # VHDL-2008
WAVE=wave.vcd

# Source files in compilation order (dependencies first)
SRCS=(
    ram.vhd
    memory.vhd          # entity name: memory  — also used as rom by memory_bus
    spi.vhd
    peripherals.vhd
    memory_bus.vhd
    cpu.vhd
    top.vhd
    cpu_tb.vhd
)

# ------------------------------------------------------------------ #
# Helpers
# ------------------------------------------------------------------ #
need() { command -v "$1" &>/dev/null || { echo "ERROR: $1 not found"; exit 1; }; }
info() { echo -e "\033[1;34m[build]\033[0m $*"; }
ok()   { echo -e "\033[1;32m[ok]\033[0m    $*"; }
err()  { echo -e "\033[1;31m[err]\033[0m   $*"; exit 1; }

usage() {
cat <<EOF
Usage: $0 [command]

Commands:
  analyse     Analyse all VHDL sources into the GHDL library
  elaborate   Elaborate the top-level entity ($TOP)
  sim         Analyse + elaborate + run simulation (produces $WAVE)
  clean       Remove all GHDL build artefacts
  vivado      Write a Vivado Tcl project script (top wrapper, 9 pins)
  help        Show this message

Default (no argument): sim
EOF
}

# ------------------------------------------------------------------ #
# Commands
# ------------------------------------------------------------------ #

do_analyse() {
    need ghdl
    info "Analysing sources (VHDL-${STD})..."
    for f in "${SRCS[@]}"; do
        if [[ ! -f "$f" ]]; then
            err "Source not found: $f"
        fi
        info "  → $f"
        ghdl -a --std=${STD} --workdir=. "$f"
    done
    ok "Analysis complete."
}

do_elaborate() {
    need ghdl
    info "Elaborating ${TOP}..."
    ghdl -e --std=${STD} --workdir=. "${TOP}"
    ok "Elaboration complete."
}

do_sim() {
    do_analyse
    do_elaborate
    info "Running simulation → ${WAVE}"
    ghdl -r --std=${STD} --workdir=. "${TOP}" \
        --vcd="${WAVE}" \
        --stop-time=10us
    ok "Simulation complete. Open with: gtkwave ${WAVE}"
}

do_clean() {
    info "Cleaning build artefacts..."
    rm -f *.o *.cf e~*.lst "${WAVE}" "${TOP}"
    ok "Clean complete."
}

do_vivado() {
    need vivado
    info "Writing Vivado project script → vivado_project.tcl"
    cat > vivado_project.tcl <<'TCL'
# Auto-generated by build.sh — 4328 CPU
create_project 4328_cpu ./vivado_proj -part xc7a35tcpg236-1 -force
set_property target_language VHDL [current_project]

# Add sources
set sources {
    ram.vhd
    memory.vhd
    peripherals.vhd
    spi.vhd
    memory_bus.vhd
    cpu.vhd
    top.vhd
}

add_files $sources

set_property FILE_TYPE {VHDL 2008} [get_files $sources]

# Add constraints
add_files -fileset constrs_1 basys3.xdc

# Set top
set_property top top [current_fileset]
update_compile_order -fileset sources_1

# Synthesise
launch_runs synth_1 -jobs 4
wait_on_run synth_1
TCL
    ok "Run with: vivado -mode batch -source vivado_project.tcl"
}

do_vivado_soc() {
    err "SoC target removed. Use 'vivado' to generate the thin-wrapper project."
}

# ------------------------------------------------------------------ #
# Entry point
# ------------------------------------------------------------------ #
CMD=${1:-sim}

case "$CMD" in
    analyse)     do_analyse     ;;
    elaborate)   do_elaborate   ;;
    sim)         do_sim         ;;
    clean)       do_clean       ;;
    vivado)      do_vivado      ;;
    vivado-soc)  do_vivado_soc  ;;
    help|-h|--help) usage       ;;
    *) err "Unknown command: $CMD  (try: $0 help)" ;;
esac
