# Auto-generated by build.sh — 4328 CPU
create_project 4328_cpu ./vivado_proj -part xc7a35tcpg236-1 -force
set_property target_language VHDL [current_project]

# Add sources
set sources {
    ram.vhd
    memory.vhd
    peripherals.vhd
    spi.vhd
    memory_bus.vhd
    cpu.vhd
    top.vhd
}

add_files $sources

set_property FILE_TYPE {VHDL 2008} [get_files $sources]

# Add constraints
add_files -fileset constrs_1 top_constraints.xdc

# Set top
set_property top top [current_fileset]
update_compile_order -fileset sources_1

# Synthesise
launch_runs synth_1 -jobs 4
wait_on_run synth_1
