// This file was generated by AI.

#include <stdio.h>
#include <string.h>
#include <ctype.h>

static int is_binary(const char *s) {
    int len = strlen(s);
    if (len == 0) return 0;
    for (int i = 0; i < len; i++) {
        if (s[i] != '0' && s[i] != '1')
            return 0;
    }
    return 1;
}

static unsigned char bin_to_byte(const char *s) {
    unsigned char v = 0;
    while (*s) {
        v <<= 1;
        v |= (*s - '0');
        s++;
    }
    return v;
}

int main(int argc, char **argv) {
    if (argc != 3) {
        printf("usage: %s input.txt output.bin\n", argv[0]);
        return 1;
    }

    FILE *in = fopen(argv[1], "r");
    FILE *out = fopen(argv[2], "wb");

    if (!in || !out) {
        perror("file error");
        return 1;
    }

    char token[256];

    while (fscanf(in, "%255s", token) == 1) {

        // HEX (detect 0x or hex digits)
        if ((token[0] == '0' && token[1] == 'x') ||
            isxdigit(token[0])) {

            unsigned int value = 0;
            sscanf(token, "%x", &value);

            unsigned char byte = (unsigned char)(value & 0xFF);
            fwrite(&byte, 1, 1, out);
        }

        // BINARY
        else if (is_binary(token)) {
            unsigned char byte = bin_to_byte(token);
            fwrite(&byte, 1, 1, out);
        }

        // ignore unknown tokens
    }

    fclose(in);
    fclose(out);

    return 0;
}
